### ISSUE TITLE
Error in magento-pwa-venia router

### ISSUE THREAD

**Issue by ksandr-dev** [magento/pwa-studio#1322]
**venia-concept/src/components/app/renderRoutes.js**
```
<Route exact path="/user/setting" component={userSetting} />
```
**venia-concept/venia-upward.yml**
```
- matches: request.url.pathname
          pattern: '^/user/setting'
          use: userSetting

... ... ...

userSetting:
    inline:
        status: 200
        headers:
            inline:
                content-type: 'text/html'
        body:
            engine: mustache
            template: './templates/userSetting-shell.mst'
            provide:
                bundles: assetManifest.bundles
                isDevelopment: isDevelopment
```

error:
![error_screen](https://user-images.githubusercontent.com/25770330/59240704-7e34f300-8c37-11e9-8def-705face547e3.png)

But in this case, router does works
**venia-concept/src/components/app/renderRoutes.js**
```
<Route exact path="/usersetting" component={userSetting} />
```
**venia-concept/venia-upward.yml**
```
- matches: request.url.pathname
          pattern: '^/usersetting'
          use: userSetting

... ... ...

userSetting:
    inline:
        status: 200
        headers:
            inline:
                content-type: 'text/html'
        body:
            engine: mustache
            template: './templates/userSetting-shell.mst'
            provide:
                bundles: assetManifest.bundles
                isDevelopment: isDevelopment
```
