### ISSUE TITLE
Integrate Page Speed Reporting into CICD process

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1712]
# Overview

Google Page Speed Insights is a subset of Lighthouse, an important tool for measuring the performance of the Venia reference PWA storefront.

<https://developers.google.com/speed/docs/insights/v5/get-started?utm_source=lh-chrome-ext>
# The Ask

Implement [page speed reporting](https://github.com/GoogleChromeLabs/psi) as part of our CI process to report on the important metrics of Google Page Speed Insights on each PR.

We want to keep performance top of mind when we're evaluating new code.

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by rasmuswikman** [comment]
I don't know if this is still relevant, but there is a GitHub action called **Lighthouse CI Action** that can do this.

https://github.com/marketplace/actions/lighthouse-ci-action

Here's a sample i ran on my Venia instance (located in `.github/workflows/lighthouse.yml`):

```yaml
# ${{ secrets.VENIA_FRONTEND_URL }}       https://venia.mydomain.com
# ${{ secrets.LHCI_GITHUB_APP_TOKEN }}    Get a token from https://github.com/apps/lighthouse-ci

name: Lighthouse
on: [push]
jobs:
  lighthouse:
    name: Lighthouse audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        with:
          urls: |
            ${{ secrets.VENIA_FRONTEND_URL }}
          temporaryPublicStorage: true
```

By supplying the `LHCI_GITHUB_APP_TOKEN` and enabling a branch protection rule in GitHub, the results can be made as status checks for pull requests. In the screenshot below, there are the performance results and by clicking "Details" you are taken to a public full report hosted for seven days at Google.

<img width="958" alt="Screenshot 2021-11-20 at 0 16 10" src="https://user-images.githubusercontent.com/72651539/142698860-218c8f29-cb67-45bb-bcb7-f3d686454349.png">

The rule I made looks like the screenshot below.

<img width="1130" alt="Screenshot 2021-11-20 at 0 16 41" src="https://user-images.githubusercontent.com/72651539/142699044-9796382a-1b7b-46fb-a26a-8e9f58c3ed39.png">

There are loads of options and thresholds that can be set, but this is the super simple version of Lighthouse CI.
