### ISSUE TITLE
[bug]: New folder in venia-static is not generated on build

### ISSUE THREAD

**Issue by LucasCalazans** [magento/pwa-studio#2468]
**Describe the bug**
I'm trying to configure a TWA (Trusted Web Activity) with our PWA Studio store, but I can't add the `.well-known/assetlinks.json` file.

This file is required on TWA.

**To reproduce**
1. Create a new project using the scaffolding command
2. Go to `<root>/upward.yml`
3. Add the following code to your upward.yml
```
veniaResponse:
  resolver: conditional
  when:
    - matches: request.url.pathname
      pattern: '^/(graphql|rest|media)(/|$)'
      use: veniaProxy
    - matches: request.url.pathname
      pattern: '^/(robots\.txt|favicon\.ico|manifest\.json)'
      use: staticFromRoot
    - matches: request.url.pathname
      pattern: '^/.well-known/assetlinks.json'
      use: staticFromRoot
    - matches: fileExtension
      pattern: '(js|json|png|svg|ico|css|txt)'
      use: veniaStatic
  default: veniaAppShell
```
4. Create these folders and file in the project root: `<root>/venia-static/.well-known/assetlinks.json` with some content in this file
5. Execute `yarn build:prod`
6. See that the folder `.well-known` was not generated in the `build` folder

**Expected behavior**
The folder `.well-known` and the `assetlinks.json` should be generated in the `build` folder

**Additional context**
It works when we try to access the file via URL (Browser) when executed via `yarn watch`. So, in development mode, we can access the file.

**Please complete the following device information:**
 - OS: **fedora 30**
 - PWA Studio Version: **6.0.1**
 - YARN version: **1.22.4**
 - Node Version: **v12.6.0**

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [x] `upward-js`
- [x] `upward-spec`
- [x] `create-pwa`

**Comment by awilcoxa** [comment]
Created PWA-667

**Comment by tjwiebell** [comment]
@LucasCalazans - [This little hint](https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/upward.yml#L126:L131) in `venia-ui/upward.yml` lead me to a solution. If you add this rule to your `upward.yml`, that should get your assets copied over.

```yaml
appStaticIncludes:
  resolver: directory
  directory:
    resolver: inline
    inline: './venia-static/.well-known'
```

Alternatively, if this file doesn't need to be nested in `venia-static`, you can serve from your own static directory and you wouldn't need to add your own conditional. Falling through to the `veniaStatic` rule would then work since the file type is json.

```yaml
appStaticIncludes:
  resolver: directory
  directory:
    resolver: inline
    inline: './static'
```

Please let me know if this doesn't solve your problem, and we'll see if there are adjustments we can make to `UpwardIncludePlugin` to make this more ergonomic.
