### ISSUE TITLE
How to parse JSON to index.html?

### ISSUE THREAD

**Issue by nickcarterney** [magento/pwa-studio#4356]
I can get data from GraphQL in upward..yml , but It's writing 

`===> Hellow ===> {{cmsPageResult &gt; json}}`

I want to print the JSON data to {{messageContent}}

```
veniaAppShell:
    resolver: inline
    inline:
        status:
            resolver: inline
            inline: 200
        headers:
            resolver: inline
            inline:
                content-type:
                    inline: text/html
                cache-control:
                    inline: s-maxage=60
        body:
            resolver: template
            engine: mustache
            provide:
                pageType: veniaPageType.data
                pageTypeNonce: veniaPageTypeNonce.nonce
                webpackChunks: veniaWebpackChunks.scripts
                **textHellow:
                    resolver: inline
                    inline: "Hellow"
                messageContent: 
                  resolver: inline
                  inline: '{{cmsPageResult > json}}' # ???? I want cmsPageResult to show as JSON in index.html**
            template:
                resolver: file
                file:
                    resolver: inline
                    inline: './index.html'


                    
cmsPageResult:
  url: 
    resolver: inline
    inline: "DOMAIN/graphql"
  query:
    resolver: inline
    inline: |
      query {
        storeConfig {
          header_logo_src
          logo_alt
          logo_height
          logo_width
          store_code
        }
      }
     
      
```

```

<!DOCTYPE html>
<html>
    <head>
        
    </head>
    <body class="bg-body text-base text-colorDefault overflow-x-hidden">
        **===> {{textHellow}}
        ===> {{messageContent}}**
    </body>
</html>

```

**Comment by nickcarterney** [comment]
@magento-admin 
@magently I am working on this

**Comment by nickcarterney** [comment]
@magento I am working on this

**Comment by nickcarterney** [comment]
@magento add to contributors team

**Comment by nickcarterney** [comment]
Can anyone help me? I cannot find any documents about this issue :(

**Comment by glo82145** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by del22123** [comment]
@nickcarterney 
Thanks for reaching out to PWA support.
Since you are using inline for messageContent, it outputs the data as string "{{cmsPageResult > json}}" instead of the actual JSON data.
Instead of using an inline string, you should reference cmsPageResult directly in the provide section, which will make the GraphQL query result available to the template.

You can reference the below example
```
veniaAppShell:
    resolver: inline
    inline:
        status:
            resolver: inline
            inline: 200
        headers:
            resolver: inline
            inline:
                content-type:
                    inline: text/html
                cache-control:
                    inline: s-maxage=60
        body:
            resolver: template
            engine: mustache
            provide:
                pageType: veniaPageType.data
                pageTypeNonce: veniaPageTypeNonce.nonce
                webpackChunks: veniaWebpackChunks.scripts
                textHellow:
                    resolver: inline
                    inline: "Hellow"
                #Reference the GraphQL result directly, not as an inline string
                storeConfig: cmsPageResult.data.storeConfig
            template:
                resolver: file
                file:
                    resolver: inline
                    inline: './index.html'

cmsPageResult:
  resolver: service
  endpoint:
    resolver: url
    baseUrl: env.MAGENTO_BACKEND_URL
    pathname:
      inline: graphql
  method:
    resolver: inline
    inline: POST
  headers:
    resolver: inline
    inline:
      'content-type': 'application/json'
      accept: 'application/json'
  query:
    resolver: inline
    inline: |
      query {
        storeConfig {
          header_logo_src
          logo_alt
          logo_height
          logo_width
          store_code
        }
      }
```

And you can update the index.html as per the below example

<!DOCTYPE html>
<html>
    <head>
        
    </head>
    <body class="bg-body text-base text-colorDefault overflow-x-hidden">
        <h2>Store Configuration:</h2>
        <ul>
            <li>Store Code: {{storeConfig.store_code}}</li>
            <li>Logo: {{storeConfig.header_logo_src}}</li>
            <li>Logo Alt: {{storeConfig.logo_alt}}</li>
            <li>Logo Dimensions: {{storeConfig.logo_width}}x{{storeConfig.logo_height}}</li>
        </ul>
    </body>
</html>

Do let us know if you need further information.
